const USER_TYPE_VIP = "VIP";
const USER_TYPE_NORMAL = "NORMAL";
const ORDER_STATUS_APPROVED = "APROVADO";

const VIP_DISCOUNT_PERCENTAGE = 0.10;
const VIP_ADDITIONAL_DISCOUNT = 50;

const DEFAULT_FREIGHT = 20;
const SAO_PAULO_FREIGHT = 5;
const CEARA_FREIGHT = 40;
const SAO_PAULO_UF = "SP";
const CEARA_UF = "CE";
const BAHIA_UF = "BH";

const VIACEP_API_URL = "https://viacep.com.br/ws";

const FREIGHT_RATES = {
  [SAO_PAULO_UF]: SAO_PAULO_FREIGHT,
  [CEARA_UF]: CEARA_FREIGHT,
};

module.exports = {
  USER_TYPE_VIP,
  USER_TYPE_NORMAL,
  ORDER_STATUS_APPROVED,
  VIP_DISCOUNT_PERCENTAGE,
  VIP_ADDITIONAL_DISCOUNT,
  DEFAULT_FREIGHT,
  VIACEP_API_URL,
  FREIGHT_RATES,
};
